# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/config.utils.ipynb.

# %% auto 0
__all__ = ['AttrDict']

# %% ../../nbs/config.utils.ipynb 3
class AttrDict(dict):
    """
    Subclass dict and define getter-setter.
    This behaves as both dict and obj.
    """

    def __getattr__(self, key):
        return self[key]

    def __setattr__(self, key, value):
        if key in self.__dict__:
            self.__dict__[key] = value
        else:
            self[key] = value
